openapi: 3.0.0
info:
  title: Square Customers API
  description: API for searching customer profiles in Square.
  version: 1.0.0
servers:
  - url: https://connect.squareup.com/v2
    description: Production server for Square API
paths:
  /customers/search:
    post:
      operationId: searchCustomers
      summary: Search for customers based on provided criteria.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: object
                  properties:
                    filter:
                      type: object
                      properties:
                        creation_source:
                          type: string
                        created_at:
                          type: object
                          properties:
                            start_at:
                              type: string
                              format: date-time
                            end_at:
                              type: string
                              format: date-time
                        updated_at:
                          type: object
                          properties:
                            start_at:
                              type: string
                              format: date-time
                            end_at:
                              type: string
                              format: date-time
                        email_address:
                          type: string
                        phone_number:
                          type: string
                        reference_id:
                          type: string
                        group_ids:
                          type: array
                          items:
                            type: string
                    sort:
                      type: object
                      properties:
                        field:
                          type: string
                        order:
                          type: string
                    limit:
                      type: integer
                    cursor:
                      type: string
      responses:
        '200':
          description: A list of customers that match the search criteria.
          content:
            application/json:
              schema:
                type: object
                properties:
                  customers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Customer'
                  cursor:
                    type: string
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
components:
  schemas:
    Customer:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        creation_source:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        email_address:
          type: string
        phone_number:
          type: string
    Error:
      type: object
      properties:
        category:
          type: string
        code:
          type: string
        detail:
          type: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
